# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

---


In [122]:
import numpy as np

# Assignment - 01: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.


In [40]:
# Part -01
arr = np.random.randint(1,21,size=(5,5))
print(f"Initial Array is:\n {arr} \n")

# Replacing all elements in the 3rd column with one
arr[0:,2:3] = np.ones((5,1))
print(f"Array after replacing 3rd column with ones: \n\n {arr}")

Initial Array is:
 [[15 10  7 16 15]
 [19  3 17  9 15]
 [ 8 18  4  4 18]
 [13 18 10  2  7]
 [ 3 18  1  3  9]] 

Array after replacing 3rd column with ones: 

 [[15 10  1 16 15]
 [19  3  1  9 15]
 [ 8 18  1  4 18]
 [13 18  1  2  7]
 [ 3 18  1  3  9]]


In [41]:
# Part -02
ar = np.random.randint(1,17,size=(4,4))
print("Before filling the diagonal with 0 \n",ar)
np.fill_diagonal(ar,0)
print("\n After filling the diagonal with zeros:\n",ar)

Before filling the diagonal with 0 
 [[ 3 16  4 11]
 [ 6  6 14  2]
 [ 6  2 12  9]
 [ 3 10 14  1]]

 After filling the diagonal with zeros:
 [[ 0 16  4 11]
 [ 6  0 14  2]
 [ 6  2  0  9]
 [ 3 10 14  0]]


---

# Assignment - 02: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.


In [53]:
# Part - 01

# b = np.random.randint(1,37,size=(6,6))

b = np.arange(1,37).reshape(6,6)
print("Initial Array:\n",b)
sub_array = b[2:5,1:4]
sub_array

Initial Array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


array([[14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

In [95]:
# Part - 02
b = np.random.randint(100,size=(5,5))
print("Initial Array:\n",b)

border_elements = np.concatenate([b[0,:],b[-1,:],b[:,0],b[:,-1]])
border_elements

Initial Array:
 [[69 46 81  7 28]
 [65 35 21 22 60]
 [88 87 20 77 80]
 [76 49 96 24 12]
 [46 89 39 83 76]]


array([69, 46, 81,  7, 28, 46, 89, 39, 83, 76, 69, 65, 88, 76, 46, 28, 60,
       80, 12, 76], dtype=int32)

---

# Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.


In [ ]:
# Part - 01
c1 = np.random.randint(30,size=(3,4))
c2 = np.random.randint(30,size=(3,4))
print("Array - 1: \n",c1)
print("Array - 2: \n",c2)

print("\nElement wise addition:\n",c1+c2)
print("\nElement wise subtraction:\n",c1-c2)
print("\nElement wise multiplication:\n",c1*c2)
print("\nElement wise division:\n",c1/c2)

Array - 1: 
 [[17 27 12  4]
 [ 2 27  9 11]
 [23 18  9 29]]
Array - 2: 
 [[12 27  7 26]
 [14 17 21 18]
 [19  3 16 15]]

Element wise addition:
 [[29 54 19 30]
 [16 44 30 29]
 [42 21 25 44]]

Element wise subtraction:
 [[  5   0   5 -22]
 [-12  10 -12  -7]
 [  4  15  -7  14]]

Element wise multiplication:
 [[204 729  84 104]
 [ 28 459 189 198]
 [437  54 144 435]]

Element wise division:
 [[1.41666667 1.         1.71428571 0.15384615]
 [0.14285714 1.58823529 0.42857143 0.61111111]
 [1.21052632 6.         0.5625     1.93333333]]


In [121]:
# Part - 02

c = np.arange(1,17).reshape(4,4)
print("Initial Array:\n",c)

row_sum = c.sum(axis=1)
print("\nSum of each row: ",row_sum)
col_sum = c.sum(axis=0)
print("Sum of each column: ",col_sum)

Initial Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Sum of each row:  [10 26 42 58]
Sum of each column:  [28 32 36 40]


---

# Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [ ]:
# Part - 01
d = np.random.randint(10,size=(5,5))
print("Initial Array:\n",d)

print(f"\n Mean:{np.mean(d)}, Median:{np.median(d)}, Standard Deviation:{np.std(d)}, Variance:{np.var(d)}")

Initial Array:
 [[6 3 7 7 4]
 [2 1 1 5 2]
 [1 2 7 8 2]
 [8 4 1 7 0]
 [7 2 4 1 4]]

 Mean:3.84, Median:4.0, Standard Deviation:2.5562472493872734, Variance:6.534400000000001


In [131]:
# Part - 02
d = np.arange(1,10).reshape(3,3)
print("Initial Array:\n",d)

normalized_array = (d-np.mean(d))/np.std(d)
print("\nNormalized Array:\n",normalized_array)

Initial Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Normalized Array:
 [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


---
# Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [137]:
# Part - 01
e = np.random.randint(100,size=(3,3))
print("Initial Array:\n",e)

array_1d = np.array([1,2,3])
print(np.shape(e), np.shape(array_1d))

broadcasted_array = e + array_1d
print("\nBroadcasted Array(add):\n",broadcasted_array)

Initial Array:
 [[73 34 21]
 [58 93 20]
 [43 57 40]]
(3, 3) (3,)

Broadcasted Array(add):
 [[74 36 24]
 [59 95 23]
 [44 59 43]]


In [139]:
# Part - 02
e = np.random.randint(100,size=(4,4))
print("Initial Array:\n",e)

array_1d = np.array([1,2,3,4])
print(np.shape(e), np.shape(array_1d))

broadcasted_array = e - array_1d
print("\nBroadcasted Array(sub):\n",broadcasted_array)

Initial Array:
 [[60 99 97  4]
 [41 41  6 98]
 [55 16 85 43]
 [85  8 58 67]]
(4, 4) (4,)

Broadcasted Array(sub):
 [[59 97 94  0]
 [40 39  3 94]
 [54 14 82 39]
 [84  6 55 63]]


---
# Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.


In [160]:
# Part - 01
f = np.array([[4,2,3],[3,5,7],[1,8,6]])
print("Initial Array:\n",f)
determinant = np.linalg.det(f)
inverse = np.linalg.inv(f)
eig_val,eig_vec = np.linalg.eig(f)

print(f"\nDeterminant: {determinant}\nInverse:\n {inverse}\n\nEigen Values: {eig_val}")

Initial Array:
 [[4 2 3]
 [3 5 7]
 [1 8 6]]

Determinant: -68.99999999999996
Inverse:
 [[ 0.37681159 -0.17391304  0.01449275]
 [ 0.15942029 -0.30434783  0.27536232]
 [-0.27536232  0.43478261 -0.20289855]]

Eigen Values: [14.00564486  2.77176996 -1.77741482]


In [159]:
# Part - 02
f1 = np.array([[1,2,3],[7,5,3]])
f2 = np.array([[3,6],[1,5],[12,9]])

print("Array 1:\n",f1)
print("Array 2:\n",f2)

mat_mul = np.dot(f1,f2)
print("Matrix Multiplication Result:\n",mat_mul)

Array 1:
 [[1 2 3]
 [7 5 3]]
Array 2:
 [[ 3  6]
 [ 1  5]
 [12  9]]
Matrix Multiplication Result:
 [[41 43]
 [62 94]]


---

# Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).


In [ ]:
# Part - 01
g = np.arange(1,10).reshape(3,3)
print("Initial array:\n",g)

print("\n Reshaping it to (1,9): \n",g.reshape(1,9))
print("\n Reshaping it back to (9,1): \n",g.reshape(9,1))

Initial array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 Reshaping it to (1,9): 
 [[1 2 3 4 5 6 7 8 9]]

 Reshaping it back to (9,1): 
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [166]:
# Part - 02
g = np.random.randint(100,size=(5,5))
print("Initial Array Before Flattening:\n",g)

flattened_array = g.flatten()
print("\n Flattened Array:\n",flattened_array)
print("\n Reshaping it back to (5,5):\n",flattened_array.reshape(5,5))

Initial Array Before Flattening:
 [[10 31 81 53 12]
 [42 96 25 46 71]
 [53 54 88 29 98]
 [38 76 67 29 82]
 [96 71 87 38 19]]

 Flattened Array:
 [10 31 81 53 12 42 96 25 46 71 53 54 88 29 98 38 76 67 29 82 96 71 87 38
 19]

 Reshaping it back to (5,5):
 [[10 31 81 53 12]
 [42 96 25 46 71]
 [53 54 88 29 98]
 [38 76 67 29 82]
 [96 71 87 38 19]]


---

# Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.


In [ ]:
# Part - 01
h = np.random.randint(100,size=(5,5))
print("Initial Array:\n",h)

# corner elements refer to the elements located at the four extreme boundary positions.
# creating rows and columns list for fancy indexing
rows= [0,0,4,4]
columns= [0,4,0,4]
print("\n Corner Elements are:\n",h[rows,columns])

Initial Array:
 [[57 50 84 38 97]
 [65 73 76 32 32]
 [55 21 84 64 89]
 [63 37 49 59 66]
 [54 75 66 43 34]]

 Corner Elements are:
 [57 97 54 34]


In [171]:
# Part - 02
h = np.random.randint(5,20,size=(4,4))
print("Initial Array:\n",h)

# boolean indexing to set elements greater than 10, to 10
h[h>10] = 10
print("\n Array after setting elements greater than 10 to 10:\n",h)

Initial Array:
 [[19 19 19  5]
 [ 5  7 10 18]
 [ 7  7  9 13]
 [ 6  5  7 18]]

 Array after setting elements greater than 10 to 10:
 [[10 10 10  5]
 [ 5  7 10 10]
 [ 7  7  9 10]
 [ 6  5  7 10]]


---

# Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.


In [ ]:
# Part - 01
# structured array data type
dt = np.dtype([('name','U10'),('age', 'i4'),('weight', 'f4')])

i = np.array([('Alice',25,55.5),('Bob',30,85.0),('Charlie',22,68.2),("Don",28,75.0)],dtype=dt)
print("\n Structured Array:\n",i)

# sort the array by age
sorted_by_age = np.sort(i,order='age')
print("\n Structured Array sorted by age:\n",sorted_by_age)


 Structured Array:
 [('Alice', 25, 55.5) ('Bob', 30, 85. ) ('Charlie', 22, 68.2)
 ('Don', 28, 75. )]

 Structured Array sorted by age:
 [('Charlie', 22, 68.2) ('Alice', 25, 55.5) ('Don', 28, 75. )
 ('Bob', 30, 85. )]


In [180]:
# Part - 02
dt = np.dtype([("x","i4"),("y","i4")])
i = np.array([(1,2),(3,4),(5,6),(7,8)],dtype=dt)
print("Structured Array:\n",i)

# calculating euclidean distance between each pair of points i.e., distance between 2 points
x1,y1 = i[0]['x'], i[0]['y']
x2,y2 = i[1]['x'], i[1]['y']
x3,y3 = i[2]['x'], i[2]['y']
x4,y4 = i[3]['x'], i[3]['y']

dist_12 = np.sqrt((x2-x1)**2 + (y2-y1)**2)
dist_23 = np.sqrt((x3-x2)**2 + (y3-y2)**2)
dist_34 = np.sqrt((x4-x3)**2 + (y4-y3)**2)
dist_41 = np.sqrt((x1-x4)**2 + (y1-y4)**2)

print(f"\n Euclidean Distances between points:\n Distance between point 1 and 2: {dist_12}\n Distance between point 2 and 3: {dist_23}\n Distance between point 3 and 4: {dist_34}\n Distance between point 4 and 1: {dist_41}")

Structured Array:
 [(1, 2) (3, 4) (5, 6) (7, 8)]

 Euclidean Distances between points:
 Distance between point 1 and 2: 2.8284271247461903
 Distance between point 2 and 3: 2.8284271247461903
 Distance between point 3 and 4: 2.8284271247461903
 Distance between point 4 and 1: 8.48528137423857


In [191]:
coords = np.column_stack((i['x'],i['y']))
print("after column stack:\n",coords)

dist_12 = np.linalg.norm(coords[1]-coords[0])
dist_23 = np.linalg.norm(coords[2]-coords[1])
dist_34 = np.linalg.norm(coords[3]-coords[2])
dist_41 = np.linalg.norm(coords[0]-coords[3])

print(f"\n Euclidean Distances between points using linalg.norm:\n Distance between point 1 and 2: {dist_12}\n Distance between point 2 and 3: {dist_23}\n Distance between point 3 and 4: {dist_34}\n Distance between point 4 and 1: {dist_41}")

after column stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

 Euclidean Distances between points using linalg.norm:
 Distance between point 1 and 2: 2.8284271247461903
 Distance between point 2 and 3: 2.8284271247461903
 Distance between point 3 and 4: 2.8284271247461903
 Distance between point 4 and 1: 8.48528137423857


---

# Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.


In [212]:
# Part - 01
j = np.random.randint(5,21,size=(4,4))
masked_array = np.ma.masked_greater(j,10)

print("Original Array:\n",j)
print("Masked Array:\n", masked_array)

unmasked_sum = np.sum(masked_array)
print(unmasked_sum)

Original Array:
 [[14 20  9 11]
 [17 14  7  5]
 [ 5 19  5 16]
 [20 11 13 10]]
Masked Array:
 [[-- -- 9 --]
 [-- -- 7 5]
 [5 -- 5 --]
 [-- -- -- 10]]
41


In [225]:
# Part - 02
j = np.random.randint(100,size=(3,3))
marr = np.ma.array(j)
marr[np.eye(marr.shape[0], dtype=bool)] = np.ma.masked

print("Original array:\n",j)
print("\nArray with masked diagonal:\n",marr)

unmasked_mean = np.mean(marr)
print("mean of unmasked elements: ",unmasked_mean)

# replace the masked elements with mean of unmasked elements
final = marr.filled(unmasked_mean)
print("\n Array final:\n",final)

Original array:
 [[19 60 31]
 [98 12 35]
 [97 88  0]]

Array with masked diagonal:
 [[-- 60 31]
 [98 -- 35]
 [97 88 --]]
mean of unmasked elements:  68.16666666666667

 Array final:
 [[68 60 31]
 [98 68 35]
 [97 88 68]]


---

# Remember !!

## 1. Fancy Indexing (Selection by Position)
You pass a list of integers to act as the indices you want to "pick out."
**Use case:** When you know the exact coordinates/positions of the data you want.

```python
import numpy as np
arr = np.array([10, 20, 30, 40, 50])

# Pass a list of indices: [pos 0, pos 4, pos 2] 
print(arr[[0, 4, 2]])  # Output: [10, 50, 30]
```

## 2. Boolean Indexing (Selection by Condition)
You pass a mask of True/False values. NumPy only returns the elements where the value is True.
**Use case:** When you want to filter data based on a mathematical rule (e.g., "all numbers > 25").

```python
arr = np.array([10, 20, 30, 40, 50])

# Create a condition (mask)
mask = arr > 25 
print(arr[mask])       # Output: [30, 40, 50]
```

### Summary Comparison

|Type  |	How it selects |	Input Example|
|---|---|---|
|Fancy | By Index/Position |	arr[[0, 3, 4]] 
|Boolean |	By Condition/Logic |	arr[arr % 2 == 0]




